
services:
  app:
    image: portainer/portainer-ce
    hostname: portainer
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /volumes/portainer_data:/data

  agent:
    image: portainer/agent:2.18.4
    restart: always
    ports:
      - "9001:9001"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /volumes/portainer_data:/var/lib/docker/volumes

