version: '3'

services:
  app:
    image: portainer/portainer-ce
    hostname: portainer
    restart: always
    ports:
      - "8012:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./volumes/portainer_data:/data
      # /var/lib/docker/volumes/portainer_portainer_data/_data
      # - portainer_data:/data
    networks:
      network:
        ipv4_address: 10.0.12.2
    #   nginx_network:
    #     ipv4_address: 10.0.2.12


  agent:
    image: portainer/agent:2.18.4
    restart: always
    ports:
      - "8112:9001"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./volumes:/var/lib/docker/volumes
      # - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      network:
        ipv4_address: 10.0.12.2



networks:
  network:
    ipam:
      config:
        - subnet: 10.0.12.0/24

# networks:
#   network:
#   nginx_network:
#     external: true
      


volumes:
  portainer_data:


