version: '3'

services:
  portainer:
    image: portainer/portainer-ce
    restart: always
    ports:
      - "8012:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./volumes/portainer_data:/data
      # /var/lib/docker/volumes/portainer_portainer_data/_data
      # - portainer_data:/data
    networks:
      net_portainer:
        ipv4_address: 10.0.1.2

  portainer_agent:
    image: portainer/agent:2.18.4
    restart: always
    ports:
      - "8013:9001"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./volumes:/var/lib/docker/volumes
      # - /var/lib/docker/volumes:/var/lib/docker/volumes

    networks:
      net_portainer:
        ipv4_address: 10.0.1.3



volumes:
  portainer_data:

networks:
  net_portainer:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.1.0/24
